### PR TITLE
Fill the name of the SecretListEntry from the GetSecretValueResponse

### PR DESCRIPTION
**Pull request by ycherkes**
Closes https://github.com/Kralizek/AWSSecretsManagerConfigurationExtensions/issues/53

### CODE REVIEW

**Comment by Kralizek** [comment]
Hi @ycherkes 
Thanks for your prompt PR to address #53 .

Could you please run something like the snippet below to show how the items are added to the configuration system?

```csharp
void Main()
{
	var configuration = new ConfigurationBuilder().AddSecretsManager().Build();
	
	foreach (var item in configuration.AsEnumerable())
	{
		Console.WriteLine($"{item.Key} = '## SECRET VALUE ##'");
	}
}
```

Just to make sure that this is the intended output :)

**Comment by H1ndo** [comment]
Hello guys, any update here?

**Comment by Kralizek** [comment]
@H1ndo sorry but at the moment I don't have capacity left for OSS development :(

**Comment by ycherkes** [comment]
> Hi @ycherkes
> Thanks for your prompt PR to address #53 .
> 
> Could you please run something like the snippet below to show how the items are added to the configuration system?
> 
> ```cs
> void Main()
> {
> 	var configuration = new ConfigurationBuilder().AddSecretsManager(o => o.AcceptedSecretArns = new[]{ "ARN", "ARN" }).Build();
> 	
> 	foreach (var item in configuration.AsEnumerable())
> 	{
> 		Console.WriteLine($"{item.Key} = '## SECRET VALUE ##'");
> 	}
> }
> ```
> 
> Just to make sure that this is the intended output :)

Hi, I'm sorry for the late response.

It adds the "secretName" key for the ARN like this `"arn:aws:secretsmanager:us-west-2:123456789012:secret:secretName-1cb5tT"`.

-- OUTPUT

`secretName =  '## SECRET VALUE ##'`

**Comment by H1ndo** [comment]
We only need to merge it now, hopefully @Kralizek will find time, thank you both.

**Comment by H1ndo** [comment]
Would bribing with cookies help here? :)

**Comment by Kralizek** [comment]
> Would bribing with cookies help here? :)

Ouch sorry! I was hoping to get this done during the weekend. I'll try to fix it tomorrow during the lunch break 😅

**Comment by Kralizek** [comment]
Merged, thanks to @ycherkes for fixing this one and sorry for those who waited so long.

**Pull request merged**
