### PR TITLE
This PR allows users to pre-filter entries in ListSecretsRequest.

### PR DESCRIPTION
**Pull request by ycherkes**
Update the AWSSDK.SecretsManager version "3.3.0" -> "3.7.0.1"

Test created and passed.

### CODE REVIEW

**Comment by Kralizek** [comment]
Hi @ycherkes, as explained [here](https://github.com/Kralizek/AWSSecretsManagerConfigurationExtensions/issues/45), I'm not accepting "dependency bump" pull requests :)

**Comment by ycherkes** [comment]
> endenc



> Hi @ycherkes, as explained [here](https://github.com/Kralizek/AWSSecretsManagerConfigurationExtensions/issues/45), I'm not accepting "dependency bump" pull requests :)
> 
> Feel free to reopen if you think closing this PR was a mistake.

Filters came with version 3.3.103. Can you accept "dependency bump" to version 3.3.103?

**Comment by Kralizek** [comment]
That could work. Would you check if #46 helps you solving your scenario?

**Comment by ycherkes** [comment]
> That could work. Would you check if #46 helps you solving your scenario?

I have seen that PR. No, it doesn't solve my scenario. In my case, we have permission for listing secrets, but we'd not like to retrieve all the secrets, just part of them.

**Comment by Kralizek** [comment]
I understand! How urgent is it? I am planning of looking at the pr by today or tomorrow

**Comment by ycherkes** [comment]
It's not very urgent.
At the moment I use the sources of your library and will replace it with a NuGet package as soon as it becomes available.
Thank you.

**Comment by ycherkes** [comment]
Also, I think, it would be great to have some logging logic here: [PollForChangesAsync](https://github.com/Kralizek/AWSSecretsManagerConfigurationExtensions/blob/master/src/Kralizek.Extensions.Configuration.AWSSecretsManager/Internal/SecretsManagerConfigurationProvider.cs#L62)
Will create a PR later.
What do you think?

**Comment by Kralizek** [comment]
hi @ycherkes

sorry for not answering to your question. we can definitely work on adding some logging in another PR. my only requirement is that works smoothly with the Microsoft ILogger system.

As for this PR, could you solve the conflicts that came after merging #46 ?

**Comment by ycherkes** [comment]
> hi @ycherkes
> 
> sorry for not answering to your question. we can definitely work on adding some logging in another PR. my only requirement is that works smoothly with the Microsoft ILogger system.
> 
> As for this PR, could you solve the conflicts that came after merging #46 ?

Done. Could you please recheck  [#46](https://github.com/Kralizek/AWSSecretsManagerConfigurationExtensions/pull/46)?

I think [there is](https://github.com/Kralizek/AWSSecretsManagerConfigurationExtensions/pull/46/files#diff-6797010e8afb2e09c7f703f69cf42a0d484674e81d226103b3c21a8b550f413cR150) an issue: must be `result.AddRange(Options.AcceptedSecretArns.Select(x => new SecretListEntry(){ARN = x, Name = x}));`

**Comment by zxsanny** [comment]
Hi guys! @ycherkes thank you for that pr, it's really what I need! @Kralizek is it possible to merge this any time soon?

**Comment by Kralizek** [comment]
@zxsanny hi,
Unfortunately nowadays I'm a bit too tight in time to be able to provide any deadline.

I'll try to allocate some time for this PR next week.

**Pull request merged**
